version: '2'
services:
  web:
    build: .
    image: ksmithorn97/qmat
    ports:
      - "9080:9080"
      - "9443:9443"
      - "7777:7777"
    volumes:
      - .:/config
    command: /opt/ibm/wlp/bin/server debug defaultServer
